//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreMVVM.Demo.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoreMVVM.Demo.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click me!.
        /// </summary>
        internal static string ClickMe {
            get {
                return ResourceManager.GetString("ClickMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        internal static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current content of the textbox is &quot;${text}&quot;..
        /// </summary>
        internal static string CurrentContent {
            get {
                return ResourceManager.GetString("CurrentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        internal static string Debug {
            get {
                return ResourceManager.GetString("Debug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug action performed. Result: success..
        /// </summary>
        internal static string DebugAction {
            get {
                return ResourceManager.GetString("DebugAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog result.
        /// </summary>
        internal static string DialogResult {
            get {
                return ResourceManager.GetString("DialogResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicking that button sent me into a state I shouldn&apos;t have been in. That&apos;s called an error..
        /// </summary>
        internal static string ErrorAction {
            get {
                return ResourceManager.GetString("ErrorAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event log:.
        /// </summary>
        internal static string EventLog {
            get {
                return ResourceManager.GetString("EventLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Exception {
            get {
                return ResourceManager.GetString("Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception was thrown by clicking that button!.
        /// </summary>
        internal static string ExceptionAction {
            get {
                return ResourceManager.GetString("ExceptionAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello World!.
        /// </summary>
        internal static string HelloWorld {
            get {
                return ResourceManager.GetString("HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        internal static string Input {
            get {
                return ResourceManager.GetString("Input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to That button click was kind of important, and has been logged..
        /// </summary>
        internal static string LogAction {
            get {
                return ResourceManager.GetString("LogAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainWindow.
        /// </summary>
        internal static string MainWindow {
            get {
                return ResourceManager.GetString("MainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix is the best movie.
        /// </summary>
        internal static string MatrixTruth {
            get {
                return ResourceManager.GetString("MatrixTruth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dialog 1.
        /// </summary>
        internal static string ShowDialog1 {
            get {
                return ResourceManager.GetString("ShowDialog1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show dialog 2.
        /// </summary>
        internal static string ShowDialog2 {
            get {
                return ResourceManager.GetString("ShowDialog2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate all fields.
        /// </summary>
        internal static string ValidateFields {
            get {
                return ResourceManager.GetString("ValidateFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You entered: ${result}.
        /// </summary>
        internal static string YouEntered {
            get {
                return ResourceManager.GetString("YouEntered", resourceCulture);
            }
        }
    }
}
